### ISSUE TITLE
Duplicate ansible_local.root.uuid, ansible_local.uuid.

### ISSUE THREAD

**Issue by ypid** [debops/ansible-core#2]
``` Python
ansible_local.root.uuid == ansible_local.uuid
```

Reason for that? ~~Currently neither are used in the DebOps project.~~ (Forgot the `--all-types` for `ag`).

**Comment by drybjed** [comment]
`ansible_local.root.uuid` is used by `debops.rsnapshot` to create unique backups for hosts if needed, and `debops.pki` to create unique ids in the certificates (stupid idea, I want to drop it in the future iterations).

I've left this because otherwise these roles would have been breaking without modifying them, and other users might have used these variables in their own setups (you never know), so I wanted to maintain backwards compatibility. `ansible_local.root.uuid` will be removed in the future.

**Comment by ypid** [comment]
All right.

**Comment by drybjed** [comment]
The fact has been removed from the `root.fact` script in the [`debops/debops`](https://github.com/debops/debops/). Closing as resolved.
