### ISSUE TITLE
Unprivileged account not needed anymore to update ansible_local.core.ansible_controllers.

### ISSUE THREAD

**Issue by ypid** [debops/ansible-core#6]
See: https://github.com/debops/ansible-bootstrap/blob/d98f350b9cb31b72c5ea0eb33abc806af96637ac/tasks/main.yml#L148

https://github.com/debops/debops-playbooks/blob/master/playbooks/core.yml needs to be updated as well.

Successfully tested it. I am reworking the docs for this role currently and will close this issue for debops.core via PR. Am I missing something here?

**Comment by drybjed** [comment]
I suppose this fix would need to be carried over to preseed / lxc template / openvz template scripts to be effective everywhere. However current method `debops.core` uses allows to gather the needed `$SSH_CLIENT` variable without the `sudo` fix present on the host. I guess it's debatable which method is better to use. At the moment `debops.core` can just be run once on a host in initial playbook and other roles don't need it running after that, since facts are already in place.

**Comment by ypid** [comment]
Thats what I missed. Thanks for the hint.
